### ISSUE TITLE
trampoline.S uservec and trampoline symbols are identical

### ISSUE THREAD

**Issue by mallicksm** [mit-pdos/xv6-riscv#113]
trap.c:100 w_stvec(TRAMPOLINE + (uservec - trampoline)) should read
w_stvec(TRAMPOLINE)

**Comment by kaashoek** [comment]
Agree doesn't break anything and is shorter.  The reason for the "+ (uservec - trampoline)" is to make sure that the user jumps to uservec, which might not be at the start of TRAMPOLINE. (Though it happens to be at the start.)  Keeping it is also makes the code symmetric for call and return.
