### ISSUE TITLE
dwarf2_find_location_expression: Corrupted DWARF expression. when printing registers using gdb

### ISSUE THREAD

**Issue by h9nara** [mit-pdos/xv6-riscv#122]
I tried to follow the gdb run in the traps & system call lecture and when I tried to print some registers with gdb, it gave 'dwarf2_find_location_expression: Corrupted DWARF expression.'. I'm using a M1 Mac if that helps.
It seems to me that tweaking some options for the compiler might fix the problem but not sure where to change. Not familiar with makefile at all.

**Comment by rapidclock** [comment]
Give this a try(https://github.com/mit-pdos/xv6-riscv/pull/129). It solved it for me.

**Comment by h9nara** [comment]
Thanks, I gave it another try recently and the exact change in your PR did fix the problem for me.
