### ISSUE TITLE
why move T_DEV check from readi/writei to FD_DEVICE check in fileread/write

### ISSUE THREAD

**Issue by brandb97** [mit-pdos/xv6-riscv#127]
I prefer the former implementation due to its uniform using of inode. Why change now? Is there any special reason?

**Comment by kaashoek** [comment]
We changed it because it is slightly strange to have the dispatch occur in fs.c, since the device isn't a file system, and it isn't necessary to chop writes in smaller pieces.  But, the old code was simpler.
