### ISSUE TITLE
can't get into the kernel if turn on qemu single step

### ISSUE THREAD

**Issue by quantrpeter** [mit-pdos/xv6-riscv#152]
Hi all
    can't get into the kernel if turn on qemu single step, please help

qemu-system-riscv64 -machine virt -bios none -kernel kernel/kernel -m 128M -smp 1 -nographic -global virtio-mmio.force-legacy=false -drive file=fs.img,if=none,format=raw,id=x0 -device virtio-blk-device,drive=x0,bus=virtio-mmio-bus.0 -singlestep -d cpu,nochain,in_asm,int -D qemu.log

thanks
Peter

**Comment by binarycraft007** [comment]
> Hi all can't get into the kernel if turn on qemu single step, please help
> 
> qemu-system-riscv64 -machine virt -bios none -kernel kernel/kernel -m 128M -smp 1 -nographic -global virtio-mmio.force-legacy=false -drive file=fs.img,if=none,format=raw,id=x0 -device virtio-blk-device,drive=x0,bus=virtio-mmio-bus.0 -singlestep -d cpu,nochain,in_asm,int -D qemu.log
> 
> thanks Peter

Hi Peter,

I have this problem too, note that you can always use web archive to access it: [link](https://web.archive.org/web/20220926041647/https://pdos.csail.mit.edu/6.S081/2022/), cheers.

Thanks,
binarycraft

**Comment by quantrpeter** [comment]
hi, i found out it is just slow, waited for 15 mins then it works
