### ISSUE TITLE
Keeping xv6-public up to date

### ISSUE THREAD

**Issue by JetStarBlues** [mit-pdos/xv6-riscv#17]
Will you be keeping the [x86 version](https://github.com/mit-pdos/xv6-public) of xv6 up to date with changes that also apply to it? I.e. changes that have nothing to do with the underlying architecture, but are instead operating system specific (for example like fixing a bug in the scheduling algorithm used, or resolving a race condition).

**Comment by judearich** [comment]
It looks like they've [added a comment](https://github.com/mit-pdos/xv6-public/commit/eeb7b415dbcb12cc362d0783e41c3d1f44066b17) to [xv6-public's](https://github.com/mit-pdos/xv6-public/blob/master/README) README which explicitly states that they've stopped maintaining it.

**Comment by JetStarBlues** [comment]
@judearich Thank you for the heads up!
