### ISSUE TITLE
Correct Document(xv6-risc) Errors

### ISSUE THREAD

**Issue by ChenMiaoi** [mit-pdos/xv6-riscv#185]
## Correct Document(xv6-risc) Errors

- Recently I was doing MIT6.S081 2021 Fall, and while reading the xv6-riscv documentation, in **Chapter 6, Section 5, the discussion of Re-entrant locks**, there is an example:

```c
struct spinlock lock;
int data = 0; // protected by lock
f() {
    acquire(&lock);
    if(data == 0) {
        call_once();
        h();
        data = 1;
    }release(&lock);
}

g() {
    aquire(&lock);
    if(data == 0) { 
        call_once();
        data = 1;
    }
    release(&lock);
}
```

- In fact, **I didn't find a definition for h()**. From a context perspective, it should be g() because Re-entrant locks cause call_once() to be called more than twice.
- I don't know if I missed it somewhere, but I did think so. If you have any questions, please let me know. thank you.

Here is what I think the version is, along with a screenshot of the original documentation:

```c
struct spinlock lock;
int data = 0; // protected by lock
f() {
    acquire(&lock);
    if(data == 0) {
        call_once();
        g(); // here, I guess it is g() not h()
        data = 1;
    }release(&lock);
}

g() {
    aquire(&lock);
    if(data == 0) { 
        call_once();
        data = 1;
    }
    release(&lock);
}
```

![The Document PDF image](https://github.com/mit-pdos/xv6-riscv/assets/96290967/b847c09b-1273-4c96-988a-643fa43d0eed)

**Comment by kaashoek** [comment]
h is intended here and refers to a hypothetical h, which is not shown.  i fixed the text to be more clear.  thx!
