### ISSUE TITLE
Broken or deprecated file `kernel/ramdisk.c`

### ISSUE THREAD

**Issue by phosphagos** [mit-pdos/xv6-riscv#188]
I'm new to xv6-riscv project and recently reading the source code. While reading and debugging, I found the source file `kernel/ramdisk.c` is dependent on the `flags` field of `struct buf` and a series of constants like `B_DIRTY`, `B_VALID`, etc., which has been removed in [This Commit](https://github.com/mit-pdos/xv6-riscv/commit/530431045237d7ccbbc0bb65ed83309845c19893). However, this file is never compiled in `Makefile`, so I wonder if it is deprecated and should be deleted now.

**Comment by kaashoek** [comment]
Thx!
