### ISSUE TITLE
xv6-riscv lacks kernal/sysinfo.h mentioned in Lab2 

### ISSUE THREAD

**Issue by ZhuEthan** [mit-pdos/xv6-riscv#23]
In [Lab2](https://pdos.csail.mit.edu/6.828/2020/labs/syscall.html), there listed a reference of kernal/sysinfo.h which cannot be found in code base. 

Could you help make that available so that consistent with the lab2 description? Thanks

**Comment by kaashoek** [comment]
You are using the wrong repo.  git clone git://g.csail.mit.edu/xv6-labs-2020, and checkout the syscall branch.
