### ISSUE TITLE
Lab pgtbl: Cannot read answers-pgtbl.txt

### ISSUE THREAD

**Issue by iefnaf** [mit-pdos/xv6-riscv#26]
I run `make grade`, but it said cannot read answers-pgtbl.txt, where is this file?
> pte printout: OK (2.1s) 
== Test answers-pgtbl.txt == answers-pgtbl.txt: FAIL 
    Cannot read answers-pgtbl.txt

**Comment by guangnianyuji** [comment]
me too,how do you fix this error,please?

**Comment by monuo2021** [comment]
You'll need to add answers-pgtbl.txt manually, just like you would add time.txt.

> 我也是，请问你如何解决这个错误？

**Comment by monuo2021** [comment]
> me too,how do you fix this error,please?

You'll need to add answers-pgtbl.txt manually, just like you would add time.txt.

**Comment by monuo2021** [comment]
In order to answer the questions that follow tasks 1 and 2, you'll need to add answers-pgtbl.txt manually, just like you would add time.txt.
