### ISSUE TITLE
xv6 kernel doesn't boot: stuck at "make qemu".

### ISSUE THREAD

**Issue by s-m-sharjeel** [mit-pdos/xv6-riscv#262]
![image](https://github.com/user-attachments/assets/c0092f9a-44ca-4313-a10d-c7a567714273)

**Comment by safwanadnan** [comment]
I'm just leaving a comment so you get a notification thinking your problem got solved but end up as disappointed and miserable as I am right now

**Comment by safwanadnan** [comment]
Try upgrading your ubuntu version to 24.xx:
sudo apt update && sudo apt full-upgrade
restart Ubuntu
sudo do-release-upgrade

Then proceed with cloning and making, worked like a charm for me

**Comment by TroyMitchell911** [comment]
please run this command `qemu-system-riscv64 -version` first and make sure your version >= 7.2
see here: 92e60dd8335b49e426760dbcbf1ef54c601f098e

if you don't wanna update your qemu, just switch to before this commit.

Glad to any help!

**Comment by Sam-x-y-z** [comment]
Any solutions? I tried everything. I'm gonna fail this course

**Comment by UKON09** [comment]
I am also stuck QAQ

**Comment by TroyMitchell911** [comment]
> I am also stuck QAQ

Check the messages I sent above

**Comment by UKON09** [comment]
The previous version of xv6 (git clone git://g.csail.mit.edu/xv6-labs-2022) and qemu (4.1.0) work!!!

**Comment by zhoujiani** [comment]
> The previous version of xv6 (git clone git://g.csail.mit.edu/xv6-labs-2022) and qemu (4.1.0) work!!!

Thank you very much, perfect solution!

**Comment by tianlanlanlan** [comment]
Remove old qemu with 'sudo apt remove qemu-system-riscv64' and:
```shell
$ sudo apt-get install git libglib2.0-dev libfdt-dev libpixman-1-dev zlib1g-dev ninja-build
$ wget https://download.qemu.org/qemu-7.2.0.tar.xz
$ tar xvf qemu-7.2.0.tar.xz 
$ cd qemu-7.2.0/
$ ./configure --disable-kvm --disable-werror --prefix=/opt/qemu-7.2.0 --target-list="riscv64-softmmu"
$ make -j 8
$ sudo make install
```
add  '/opt/qemu-7.2.0/bin' to your ~/.bashrc PATH

**Comment by QueenOfBees** [comment]
> The previous version of xv6 (git clone git://g.csail.mit.edu/xv6-labs-2022) and qemu (4.1.0) work!!!XV6（git clone git：//g.csail.mit.edu/xv6-labs-2022）和qemu（4.1.0）工作的先前版本！！！

Good solution. 
I am using ubuntu-2024, all third dependency is latest. It turns out xv6-labs-2020 did not work, but xv6-labs-2022 works fine.

**Comment by markus-zhang** [comment]
Thanks @tianlanlanlan this works perfectly for me.
For others, I believe this method also preserves the home qemu if you so wish as it installs the qemu under `opt`.

Also it is fun to watch qemu builds for one hour :)

**Comment by wave-sky** [comment]
> The previous version of xv6 (git clone git://g.csail.mit.edu/xv6-labs-2022) and qemu (4.1.0) work!!!
Thank you very much!

**Comment by spookier** [comment]
Even after running this, I encountered the "silent freeze" where make qemu starts but produces no output
I managed to fix it tho, it's _"caused by ISA/ABI mismatches between modern toolchains (GCC 15.2.0+) and QEMU 7.2.0"_

### Fix:
#### I modified the Makefile and added these 2:

```Makefile
# Added in CFLAGS section:
  CFLAGS += -march=rv64gc
  CFLAGS += -mabi=lp64
```

```Makefile
# Updated kernel assembly compile rule
  $K/%.o: $K/%.S
  	$(CC) $(CFLAGS) -g -c -o $@ $<
```


Apparently newer GCC versions default to RISC-V extensions incompatible with older QEMU versions, causing the kernel to hang before initializing the console


> Remove old qemu with 'sudo apt remove qemu-system-riscv64' and:
> 
> $ sudo apt-get install git libglib2.0-dev libfdt-dev libpixman-1-dev zlib1g-dev ninja-build
> $ wget https://download.qemu.org/qemu-7.2.0.tar.xz
> $ tar xvf qemu-7.2.0.tar.xz 
> $ cd qemu-7.2.0/
> $ ./configure --disable-kvm --disable-werror --prefix=/opt/qemu-7.2.0 --target-list="riscv64-softmmu"
> $ make -j 8
> $ sudo make install
> add '/opt/qemu-7.2.0/bin' to your ~/.bashrc PATH
