### ISSUE TITLE
Macro definition 'O_CREATE' missing a letter 'E' in line 88 of file mkfs/mkfs.c

### ISSUE THREAD

**Issue by BGMyang** [mit-pdos/xv6-riscv#270]
Macro definition 'O_CREATE' missing a letter 'E' in line 88 of file mkfs/mkfs.c

**Comment by jrmenzel** [comment]
This is actually a bug in the original UNIX. Ken Thompson, one of the original creators once joked that his biggest regret in designing UNIX was writing "create" without the "e".

Here is the function define in the original version 6 UNIX (the one xv6 is based on): https://github.com/dspinellis/unix-history-repo/blob/Research-V6-Snapshot-Development/usr/sys/ken/sys2.c?plain=1#L78

As you can see in the man page of Linux, "create" is still missing the "e" in both the function call and the define: https://man7.org/linux/man-pages/man2/open.2.html .

**Comment by BGMyang** [comment]
Thank you for your answer
