### ISSUE TITLE
Why don't need clean bss seg in exec?

### ISSUE THREAD

**Issue by TroyMitchell911** [mit-pdos/xv6-riscv#273]
I write a os like xv6.

but I need to clean bss segment otherwise global variable that equals 0 gets a random value in user program.

**Comment by jrmenzel** [comment]
Exec in xv6 loads the program into memory in exec.c:53 (https://github.com/mit-pdos/xv6-riscv/blob/riscv/kernel/exec.c?plain=1#L53). The memory for the app gets allocated in uvmalloc(). There you can see, that *all* pages given to the app are cleared to 0. BSS also gets this treatment, but not explicitly only BSS (e.g. code pages will get cleared and then filled with the code): https://github.com/mit-pdos/xv6-riscv/blob/riscv/kernel/vm.c?plain=1#L248 .

**Comment by TroyMitchell911** [comment]
> Exec in xv6 loads the program into memory in exec.c:53 (https://github.com/mit-pdos/xv6-riscv/blob/riscv/kernel/exec.c?plain=1#L53). The memory for the app gets allocated in uvmalloc(). There you can see, that _all_ pages given to the app are cleared to 0. BSS also gets this treatment, but not explicitly only BSS (e.g. code pages will get cleared and then filled with the code): https://github.com/mit-pdos/xv6-riscv/blob/riscv/kernel/vm.c?plain=1#L248 .

I get it. and I call `memset` too. but the BSS is wrong...

I will try to get rid of clean BSS after `loadseg`(maybe after vm_map).

**Comment by TroyMitchell911** [comment]
reason: load segment size should be ph.filesz instead of ph.memsz.
