### ISSUE TITLE
Unable to run properly in MacBook m1

### ISSUE THREAD

**Issue by MrZLeo** [mit-pdos/xv6-riscv#83]
I download the necessary dependencies and type `make qemu` in xv6's directory, it seems some troubles happened:
```
qemu-system-riscv64 -machine virt -bios none -kernel kernel/kernel -m 128M -smp 3 -nographic -drive file=fs.img,if=none,format=raw,id=x0 -device virtio-blk-device,drive=x0,bus=virtio-mmio-bus.0
qemu-system-riscv64: qemu_mprotect__osdep: mprotect failed: Permission denied
qemu-system-riscv64: qemu_mprotect__osdep: mprotect failed: Permission denied
qemu-system-riscv64: qemu_mprotect__osdep: mprotect failed: Permission denied
qemu-system-riscv64: qemu_mprotect__osdep: mprotect failed: Permission denied
qemu-system-riscv64: qemu_mprotect__osdep: mprotect failed: Permission denied
qemu-system-riscv64: qemu_mprotect__osdep: mprotect failed: Permission denied
qemu-system-riscv64: qemu_mprotect__osdep: mprotect failed: Permission denied
qemu-system-riscv64: qemu_mprotect__osdep: mprotect failed: Permission denied
qemu-system-riscv64: qemu_mprotect__osdep: mprotect failed: Permission denied
qemu-system-riscv64: qemu_mprotect__osdep: mprotect failed: Permission denied
qemu-system-riscv64: qemu_mprotect__osdep: mprotect failed: Permission denied
qemu-system-riscv64: qemu_mprotect__osdep: mprotect failed: Permission denied
qemu-system-riscv64: qemu_mprotect__osdep: mprotect failed: Permission denied
qemu-system-riscv64: qemu_mprotect__osdep: mprotect failed: Permission denied
qemu-system-riscv64: qemu_mprotect__osdep: mprotect failed: Permission denied
qemu-system-riscv64: qemu_mprotect__osdep: mprotect failed: Permission denied
qemu-system-riscv64: qemu_mprotect__osdep: mprotect failed: Permission denied
qemu-system-riscv64: qemu_mprotect__osdep: mprotect failed: Permission denied
qemu-system-riscv64: qemu_mprotect__osdep: mprotect failed: Permission denied
qemu-system-riscv64: qemu_mprotect__osdep: mprotect failed: Permission denied
qemu-system-riscv64: qemu_mprotect__osdep: mprotect failed: Permission denied
qemu-system-riscv64: qemu_mprotect__osdep: mprotect failed: Permission denied
qemu-system-riscv64: qemu_mprotect__osdep: mprotect failed: Permission denied
qemu-system-riscv64: qemu_mprotect__osdep: mprotect failed: Permission denied
```

I don't know what does it means and how to solve it. But it seems I have to exit it by `ctrl + A + x` rather than `ctrl + c`, which indicates that the problem may come from qemu.

My device:
```
MacBook Pro m1,
macOS 11.4,
qemu 6.0,
riscv64-unknown-elf-gcc (GCC) 10.2.0
```

**Comment by MrZLeo** [comment]
And I have tried `sudo make qemu` as well, it did not work.

**Comment by inPhraZ** [comment]
If your qemu version is v5.0 (`$ qemu-system-riscv64  --version`), then this message comes from [`qemu_mprotect__osdep`](https://github.com/qemu/qemu/blob/53f306f316549d20c76886903181413d20842423/util/osdep.c#L93). `qemu_mprotect__osdep` will call `mprotect` function in non windows machines.

It has been observed that mprotect has an error in m1. (see [here](https://www.mail-archive.com/qemu-devel@nongnu.org/msg781329.html))

mprotect itself is called in another function called `qemu_mprotect_none`
and there is a for loop in [`tcg_region_init`](https://github.com/qemu/qemu/blob/386b2a5767f7642521cd07930c681ec8a6057e60/tcg/tcg.c#L718) which calls `qemu_mprotect_none`.
This loop sets the guard pages for security issues.

So clone qemu and [checkout  v5.0](https://risc-v-getting-started-guide.readthedocs.io/en/latest/linux-qemu.html), then make changes shown in [this link](https://gitlab.com/qemu-project/qemu/-/commit/c118881ee607dcac) and build the qemu. This may temporarily fix the problem.

I'm not sure.... But I hope it would be helpful.

**Comment by TrenDavi** [comment]
I am running Qemu on a M1 too. Ending up having the exact same error when trying to boot. :(

**Comment by knightsc** [comment]
The comments on this thread make it sound like Qemu was patched in May to address this issue.

https://bugs.launchpad.net/qemu/+bug/1914849

Perhaps try using Qemu 6.1.0

**Comment by tresf** [comment]
I'm not sure if this is the right place to post this, but at time of writing this, homebrew has `qemu` 7.2.0, which works pretty well with riscv.

<img width="890" alt="image" src="https://user-images.githubusercontent.com/6345473/213847706-da541f49-7ea6-45bc-a7d6-a6ea0dc2c100.png">

Command:

```bash
qemu-system-riscv64 \
    -machine virt \
    -cpu rv64 \
    -m 4G \
    -device virtio-blk-device,drive=hd \
    -drive file=overlay.qcow2,if=none,id=hd \
    -device virtio-net-device,netdev=net \
    -netdev user,id=net,hostfwd=tcp::2222-:22 \
    -kernel ./u-boot-qemu/uboot.elf \ # extracted from u-boot-qemu_2021.01+dfsg-5_all.deb
    -object rng-random,filename=/dev/urandom,id=rng \
    -device virtio-rng-device,rng=rng \
    -append "root=LABEL=rootfs console=ttyS0" \
    -nographic
```

**Comment by MrZLeo** [comment]
@tresf Yes, it works now. It has been supported by qemu right now : )
