### ISSUE TITLE
can not `make grade`

### ISSUE THREAD

**Issue by hanzizhao1998** [mit-pdos/xv6-riscv#88]
in my zsh, I want to check code

$ make grade
make: *** No rule to make target `grade'.  Stop.

should I modify Makefile?

and I can't find the python srcipt grade-lab-util sleep

**Comment by pxng123** [comment]
我也遇到这个问题了  咋回事啊o(╥﹏╥)o

**Comment by meerci** [comment]
git clone git://g.csail.mit.edu/xv6-labs-2024
